spring:
  datasource:
    url: jdbc:h2:mem:commentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: commentproject
    password: "commentatorpassword"
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

resilience4j.ratelimiter:
  instances:
    commentLimiter:
      limit-for-period: 1
      limit-refresh-period: 10s
      timeout-duration: 0

